Asp.net/Models/ErrorViewModel.cs
namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Asp.net/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult You()
        {
            return View();
        }
        public IActionResult Me()
        {
            return View();
        }
    }
}

Asp.net/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ContactNumber()
        {
            return View();
        }
        public IActionResult ContactCharge()
        {
            return View();
        }
    }
}

Asp.net/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Asp.net/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Price()
        {
            return View();
        }
        public IActionResult Item()
        {
            return View();
        }
    }
}

Asp.net/Views/About/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>About-Index</h1>

Asp.net/Views/About/Me.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<form>
    <div class="mb-3">
        <label for="empid" class="form-label">EmpID</label>
        <input type="number" class="form-control" id="empid">
    </div>
    <div class="mb-3">
        <label for="empname" class="form-label">EmpName</label>
        <input type="text" class="form-control" id="empname">
    </div>
    <div class="mb-3">
        <label for="empcode" class="form-label">EmpCode</label>
        <input type="text" class="form-control" id="empcode">
    </div>
    <div class="mb-3">
        <label for="Salary" class="form-label">Salary</label>
        <input type="number" class="form-control" id="Salary">
    </div>
    <div class="dropdown">
        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Designation
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="HOD">HOD</a></li>
            <li><a class="dropdown-item" href="Admin">Admin</a></li>
            <li><a class="dropdown-item" href="Manager">Manager</a></li>
        </ul>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

Asp.net/Views/About/You.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<table class="table">
    <a class="btn btn-primary " tabindex="-1" role="button" aria-disabled="false" asp-area="" asp-controller="About" asp-action="Me">Add</a>
    <thead>
        <tr>
            <th scope="col">EmployeeID</th>
            <th scope="col">EmployeeName</th>
            <th scope="col">EmployeeCode</th>
            <th scope="col">Salary</th>
            <th scope="col">Designation</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>101</td>
            <td>Mark</td>
            <td>2AC</td>
            <td>20000</td>
            <td>HR</td>
            <td><i class="bi bi-pencil-square"></i></td>
            <td><i class="bi bi-x-square"></i></td>
        </tr>
        <tr>
            <td>102</td>
            <td>Otto</td>
            <td>2AZ</td>
            <td>60000</td>
            <td>Admin</td>
            <td><i class="bi bi-pencil-square"></i></td>
            <td><i class="bi bi-x-square"></i></td>
        </tr>
        <tr>
            <td>103</td>
            <td>Mark</td>
            <td>2AF</td>
            <td>8000</td>
            <td>HOD</td>
            <td><i class="bi bi-pencil-square"></i></td>
            <td><i class="bi bi-x-square"></i></td>
        </tr>
    </tbody>
</table>

Asp.net/Views/Contact/ContactCharge.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>Conact-ContactCharge</h1>

Asp.net/Views/Contact/ContactNumber.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>Conact-ContactNumber</h1>

Asp.net/Views/Contact/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>Contact-Index</h1>

Asp.net/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Asp.net/Views/Product/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>Product Index</h1>

Asp.net/Views/Product/Item.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>Product Item </h1>

Asp.net/Views/Product/Price.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>Product Price </h1>

Asp.net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product_Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Price">Product_Price</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Item">Product_Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact_Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="ContactCharge">Contact_ContactCharge</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="ContactNumber">Contact_ContactNumber</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About_Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="You">About_You</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Me">About_Me</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>